create table cliente (fecha_nacimiento date, sexo tinyint, id bigint not null, id_centro bigint, id_usuario bigint, direccion varchar(255), dni varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente_seq (next_val bigint) engine=InnoDB;
insert into cliente_seq values ( 1 );
create table mensaje_cliente_seq (next_val bigint) engine=InnoDB;
insert into mensaje_cliente_seq values ( 1 );
create table mensaje_cliente (cliente_id bigint, id bigint not null, id_destinatario bigint, asunto varchar(255), contenido varchar(255), tipo enum ('CENTRO','ENTRENADOR','CLIENTE'), primary key (id)) engine=InnoDB;
create table mensaje_cliente_copia (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_copia_oculta (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_destinatarios (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
alter table mensaje_cliente add constraint FKml5gaaitecmos69msr3bo3ua7 foreign key (cliente_id) references cliente (id);
alter table mensaje_cliente_copia add constraint FKdn7cmr0lkx6xore5597sww68o foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_copia_oculta add constraint FKqa7n6qjbnyqnm53st3golw0de foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_destinatarios add constraint FKaoud9q0gys82htt490bbhj7cd foreign key (mensaje_cliente_id) references mensaje_cliente (id);
create table cliente (fecha_nacimiento date, sexo tinyint, id bigint not null, id_centro bigint, id_usuario bigint, direccion varchar(255), dni varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente_seq (next_val bigint) engine=InnoDB;
insert into cliente_seq values ( 1 );
create table mensaje_cliente_seq (next_val bigint) engine=InnoDB;
insert into mensaje_cliente_seq values ( 1 );
create table mensaje_cliente (cliente_id bigint, id bigint not null, id_destinatario bigint, asunto varchar(255), contenido varchar(255), tipo enum ('CENTRO','ENTRENADOR','CLIENTE'), primary key (id)) engine=InnoDB;
create table mensaje_cliente_copia (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_copia_oculta (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_destinatarios (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
alter table mensaje_cliente add constraint FKml5gaaitecmos69msr3bo3ua7 foreign key (cliente_id) references cliente (id);
alter table mensaje_cliente_copia add constraint FKdn7cmr0lkx6xore5597sww68o foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_copia_oculta add constraint FKqa7n6qjbnyqnm53st3golw0de foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_destinatarios add constraint FKaoud9q0gys82htt490bbhj7cd foreign key (mensaje_cliente_id) references mensaje_cliente (id);
create table cliente (fecha_nacimiento date, sexo tinyint, id bigint not null, id_centro bigint, id_usuario bigint, direccion varchar(255), dni varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente_seq (next_val bigint) engine=InnoDB;
insert into cliente_seq values ( 1 );
create table mensaje_cliente_seq (next_val bigint) engine=InnoDB;
insert into mensaje_cliente_seq values ( 1 );
create table mensaje_cliente (cliente_id bigint, id bigint not null, id_destinatario bigint, asunto varchar(255), contenido varchar(255), tipo enum ('CENTRO','ENTRENADOR','CLIENTE'), primary key (id)) engine=InnoDB;
create table mensaje_cliente_copia (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_copia_oculta (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_destinatarios (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
alter table mensaje_cliente add constraint FKml5gaaitecmos69msr3bo3ua7 foreign key (cliente_id) references cliente (id);
alter table mensaje_cliente_copia add constraint FKdn7cmr0lkx6xore5597sww68o foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_copia_oculta add constraint FKqa7n6qjbnyqnm53st3golw0de foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_destinatarios add constraint FKaoud9q0gys82htt490bbhj7cd foreign key (mensaje_cliente_id) references mensaje_cliente (id);
create table cliente (fecha_nacimiento date, sexo tinyint, id bigint not null, id_centro bigint, id_usuario bigint, direccion varchar(255), dni varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente_seq (next_val bigint) engine=InnoDB;
insert into cliente_seq values ( 1 );
create table mensaje_cliente_seq (next_val bigint) engine=InnoDB;
insert into mensaje_cliente_seq values ( 1 );
create table mensaje_cliente (cliente_id bigint, id bigint not null, id_destinatario bigint, asunto varchar(255), contenido varchar(255), tipo enum ('CENTRO','ENTRENADOR','CLIENTE'), primary key (id)) engine=InnoDB;
create table mensaje_cliente_copia (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_copia_oculta (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_destinatarios (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
alter table mensaje_cliente add constraint FKml5gaaitecmos69msr3bo3ua7 foreign key (cliente_id) references cliente (id);
alter table mensaje_cliente_copia add constraint FKdn7cmr0lkx6xore5597sww68o foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_copia_oculta add constraint FKqa7n6qjbnyqnm53st3golw0de foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_destinatarios add constraint FKaoud9q0gys82htt490bbhj7cd foreign key (mensaje_cliente_id) references mensaje_cliente (id);
create table cliente (fecha_nacimiento date, sexo tinyint, id bigint not null, id_centro bigint, id_usuario bigint, direccion varchar(255), dni varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente_seq (next_val bigint) engine=InnoDB;
insert into cliente_seq values ( 1 );
create table mensaje_cliente_seq (next_val bigint) engine=InnoDB;
insert into mensaje_cliente_seq values ( 1 );
create table mensaje_cliente (cliente_id bigint, id bigint not null, id_destinatario bigint, asunto varchar(255), contenido varchar(255), tipo enum ('CENTRO','ENTRENADOR','CLIENTE'), primary key (id)) engine=InnoDB;
create table mensaje_cliente_copia (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_copia_oculta (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_destinatarios (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
alter table mensaje_cliente add constraint FKml5gaaitecmos69msr3bo3ua7 foreign key (cliente_id) references cliente (id);
alter table mensaje_cliente_copia add constraint FKdn7cmr0lkx6xore5597sww68o foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_copia_oculta add constraint FKqa7n6qjbnyqnm53st3golw0de foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_destinatarios add constraint FKaoud9q0gys82htt490bbhj7cd foreign key (mensaje_cliente_id) references mensaje_cliente (id);
create table cliente (fecha_nacimiento date, sexo tinyint, id bigint not null, id_centro bigint, id_usuario bigint, direccion varchar(255), dni varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente_seq (next_val bigint) engine=InnoDB;
insert into cliente_seq values ( 1 );
create table mensaje_cliente_seq (next_val bigint) engine=InnoDB;
insert into mensaje_cliente_seq values ( 1 );
create table mensaje_cliente (cliente_id bigint, id bigint not null, id_destinatario bigint, asunto varchar(255), contenido varchar(255), tipo enum ('CENTRO','ENTRENADOR','CLIENTE'), primary key (id)) engine=InnoDB;
create table mensaje_cliente_copia (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_copia_oculta (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_destinatarios (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
alter table mensaje_cliente add constraint FKml5gaaitecmos69msr3bo3ua7 foreign key (cliente_id) references cliente (id);
alter table mensaje_cliente_copia add constraint FKdn7cmr0lkx6xore5597sww68o foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_copia_oculta add constraint FKqa7n6qjbnyqnm53st3golw0de foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_destinatarios add constraint FKaoud9q0gys82htt490bbhj7cd foreign key (mensaje_cliente_id) references mensaje_cliente (id);
create table cliente (fecha_nacimiento date, sexo tinyint, id bigint not null, id_centro bigint, id_usuario bigint, direccion varchar(255), dni varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente_seq (next_val bigint) engine=InnoDB;
insert into cliente_seq values ( 1 );
create table mensaje_cliente_seq (next_val bigint) engine=InnoDB;
insert into mensaje_cliente_seq values ( 1 );
create table mensaje_cliente (cliente_id bigint, id bigint not null, id_destinatario bigint, asunto varchar(255), contenido varchar(255), tipo enum ('CENTRO','ENTRENADOR','CLIENTE'), primary key (id)) engine=InnoDB;
create table mensaje_cliente_copia (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_copia_oculta (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_destinatarios (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
alter table mensaje_cliente add constraint FKml5gaaitecmos69msr3bo3ua7 foreign key (cliente_id) references cliente (id);
alter table mensaje_cliente_copia add constraint FKdn7cmr0lkx6xore5597sww68o foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_copia_oculta add constraint FKqa7n6qjbnyqnm53st3golw0de foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_destinatarios add constraint FKaoud9q0gys82htt490bbhj7cd foreign key (mensaje_cliente_id) references mensaje_cliente (id);
create table cliente (fecha_nacimiento date, sexo tinyint, id bigint not null, id_centro bigint, id_usuario bigint, direccion varchar(255), dni varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente_seq (next_val bigint) engine=InnoDB;
insert into cliente_seq values ( 1 );
create table mensaje_cliente_seq (next_val bigint) engine=InnoDB;
insert into mensaje_cliente_seq values ( 1 );
create table mensaje_cliente (cliente_id bigint, id bigint not null, id_destinatario bigint, asunto varchar(255), contenido varchar(255), tipo enum ('CENTRO','ENTRENADOR','CLIENTE'), primary key (id)) engine=InnoDB;
create table mensaje_cliente_copia (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_copia_oculta (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_destinatarios (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
alter table mensaje_cliente add constraint FKml5gaaitecmos69msr3bo3ua7 foreign key (cliente_id) references cliente (id);
alter table mensaje_cliente_copia add constraint FKdn7cmr0lkx6xore5597sww68o foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_copia_oculta add constraint FKqa7n6qjbnyqnm53st3golw0de foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_destinatarios add constraint FKaoud9q0gys82htt490bbhj7cd foreign key (mensaje_cliente_id) references mensaje_cliente (id);
create table cliente (fecha_nacimiento date, sexo tinyint, id bigint not null, id_centro bigint, id_usuario bigint, direccion varchar(255), dni varchar(255), telefono varchar(255), primary key (id)) engine=InnoDB;
create table cliente_seq (next_val bigint) engine=InnoDB;
insert into cliente_seq values ( 1 );
create table mensaje_cliente_seq (next_val bigint) engine=InnoDB;
insert into mensaje_cliente_seq values ( 1 );
create table mensaje_cliente (cliente_id bigint, id bigint not null, id_destinatario bigint, asunto varchar(255), contenido varchar(255), tipo enum ('CENTRO','ENTRENADOR','CLIENTE'), primary key (id)) engine=InnoDB;
create table mensaje_cliente_copia (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_copia_oculta (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
create table mensaje_cliente_destinatarios (id_destinatario bigint, mensaje_cliente_id bigint not null, tipo enum ('CENTRO','ENTRENADOR','CLIENTE')) engine=InnoDB;
alter table mensaje_cliente add constraint FKml5gaaitecmos69msr3bo3ua7 foreign key (cliente_id) references cliente (id);
alter table mensaje_cliente_copia add constraint FKdn7cmr0lkx6xore5597sww68o foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_copia_oculta add constraint FKqa7n6qjbnyqnm53st3golw0de foreign key (mensaje_cliente_id) references mensaje_cliente (id);
alter table mensaje_cliente_destinatarios add constraint FKaoud9q0gys82htt490bbhj7cd foreign key (mensaje_cliente_id) references mensaje_cliente (id);
